### ISSUE TITLE
US 01.06.01 - see the total number of QRcodes that have been scanned

### ISSUE THREAD

**Issue by lawrence080** [CMPUT301W23T41/SnailsCurlUp#20]

**Comment by JKHellNo** [comment]
count() aggregation to return the total number of QR in the a user, QRList collection.

**Comment by JKHellNo** [comment]
I have the query ready but i don't know the appropriate place to place it.

**Comment by Zgell** [comment]
@JKHellNo an easier way might actually be to count it locally instead of doing it as a query so that we can lighten the load on our database. As in, use the database to load in which QR codes a user has attached to them, and then count the number of loaded QR codes locally in the app. Might be best to minimize the number of DB operations since I don't know what the limitations of the Firebase API are, and I don't want to find out.

**Comment by Zgell** [comment]
Also, this is something simple I can fix a little bit later, probably alongside 01.05.01.

**Comment by JKHellNo** [comment]
count() just returns number of documents inside a collection. Its 1 DB op, or we just update the data field "Codes scanned" inside Users Collection. Loading in QR codes a user has means that the DB operations will be equal to the number of QR code as the ID of each will be returned.

**Comment by Zgell** [comment]
This has been included in the `QrCodeFunc` branch, and will be marked as done when it is merged in.

**Comment by Zgell** [comment]
This is now done and in master. Closing now
