### ISSUE TITLE
US 04.02.01 Login using device identification instead of username and password

### ISSUE THREAD

**Issue by GordonGu1900** [CMPUT301W23T41/SnailsCurlUp#24]
US 04.02.01 
As a player, I do not want to log into my application using a username and password as my device can identify me.

Story point: L(5)
Risk level: Medium

**Comment by Zgell** [comment]
This has been satisfied with the addition of the partial user profile, but I think we should meet with the TA at some point to confirm whether or not this is the best approach. Once we get better control over locally-saved data this will be less of a problem.

**Comment by AyanB123** [comment]
Yes i agree i think we need set up with database verification

**Comment by JKHellNo** [comment]
We're not designing 2FA. There's a reason why you it's worded that you don't need to enter the username as well. Otherwise if you have multiple accounts, then you enter username, and the password is essentially Device ID. This checks against the database for list of devices under a username.

Instead the device stores everything(assuming alongside password, but that isn't a thing), and we do not need to set up a 2FA type feature, checks password and a valid device. Because the idea is that you should be able to login through different device and this particular issue is ultimately one of convenience where you can store all your information.
