### ISSUE TITLE
US 06.01.01 show map of geo-locations of nearby QR codes

### ISSUE THREAD

**Issue by GordonGu1900** [CMPUT301W23T41/SnailsCurlUp#27]
US 06.01.01

As a player, I want to see a map of geo-locations of nearby QR codes.

Story points: L(5)
Risk level: Medium

**Comment by Zgell** [comment]
One thing I'd like to note for the future on this one is that we'll definitely have to use a third-party library to handle the map. My recommendation would be something like OpenStreetMap (basically like an open source Google Maps API), but it'll be a fair bit of work to integrate that properly into the app. This story will definitely need to be broken down into smaller pieces.

**Comment by Zgell** [comment]
Update: Made a map for this, but couldn't add markers/camera movement to it. Found out that the issue was with running maps in Fragments versus Activities. Currently reworking app structure to accommodate for the necessity of multiple activities.

For those who are running into similar activity-related issues: [see this article on how to create multiple activities, switch between them and transfer data between them](https://learntodroid.com/how-to-switch-between-activities-in-android/)

**Comment by Zgell** [comment]
Another Update: Got the new map system working using an activity. Just sorting out a bug with fragments vs. activities and can have a pull request up soon.

**Comment by Zgell** [comment]
This is now merged into master, so I'm closing the issue.
