### ISSUE TITLE
US 02.04.01-  Player see's Players have same QR code scanned

### ISSUE THREAD

**Issue by AyanB123** [CMPUT301W23T41/SnailsCurlUp#28]
US 02.04.01
As a player, I want to see that other players have scanned the same QR code.
Story Points: M(3)
Risk Level: LOW

**Comment by Zgell** [comment]
Because of the rework related to comments where they now pertain to QR codes in a global sense (ie. any comment made on any QR instance will show up in all other QR instances of the same type, as comments are tied to the Abstract QR), this is *technically* satisfied now using the comments system. I think there might be an improved implementation coming later now. Marking as done for now.
