### ISSUE TITLE
US 02.06.01 - add unique visual representation for every QR code

### ISSUE THREAD

**Issue by AyanB123** [CMPUT301W23T41/SnailsCurlUp#31]
US 02.06.01
As a player, I want to see a visual representation of a QR code relatively unique to that QR code.
Story Points: M(3)
Risk Level: LOW

**Comment by Zgell** [comment]
Random thought: if we're doing this the way it was suggested on eClass (using ASCII art for the visualization), we should definitely use a monospace font of some kind to represent it, otherwise it will be a total nightmare to design. We could also look into some kind of very basic image generation (maybe something analogous to how GitHub auto-generates profile pictures?) as well. We'll need to discuss this further.

**Comment by Zgell** [comment]
Now that we know from our TA that we're allowed to use the images generated by the Picasso API for the QR codes, this issue is done for now. We can always revisit this later if we decide we don't like the images it generates.
